# Generated by Django 5.2.4 on 2025-08-12 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfumes/'),
        ),
    ]
