# Generated by Django 5.2.4 on 2025-08-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0002_perfume_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='perfume',
            name='precio_descuento',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
